a = set()

n = input("enter your number: ")
a.add(int(n))
n = input("enter your number: ")
a.add(int(n))
n = input("enter your number: ")
a.add(int(n))
n = input("enter your number: ")
a.add(int(n))
n = input("enter your number: ")
a.add(int(n))
n = input("enter your number: ")
a.add(int(n))
print(a)
